
# html lang
language: en

# seo优化
seo:
 keywords: "大海"
 description: "no description"

# Miscelaneous
favicon: /source/favicon.ico

# head-bg 头像背景图 
headbg: /images/header-bg.png
# header 头像图 
header: /images/header.png

# post-header 标语部分
post_header:
  img: /images/cover.png
  about:
    - "踏实一些，不要着急，你想要的，岁月都会给你。"
  url: "https://bigsea001.github.io"
  visitor_front: "你是第"
  visitor_back: "位访客"

# 主配色
blendent:
  main: "#26A69A"

#访客
visitor: false

#博客时间统计
time: false
#博客开启的时间 格式为：月/日/年 几点:几分:几秒
begin_time: 1/1/2017 00:00:00

#链接
sns:
    github: "https://bigsea001.github.io"
#    weibo: "http://example.com"
#    zhihu: "http://example.com"
#    twitter: "http://example.com"
#    email: "http://example.com"

#默认thumbnail图片的数目
thumbnail: 19

#nav
sidebar:
    homepage:
        use: true
    archives:
        use: true
    categories:
        use: true
    tags:
        use: true
    about:
        use: false
    friends:
        use: false
    photo:
        use: false

# Reading experience
reading:
    entry_excerpt: 180

#photo page
photo:
    name: "影集名称"
    about: "一段简介"

#评论
comment:
    use: false
    shortname: XXX.disqus.com

# stylesheets loaded in the <head>
stylesheets:
  - /css/materialize.min.css
  - /css/main.min.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.1.1.min.js
  - /js/materialize.min.js
  - /js/main.min.js



